import 'package:get/get.dart';

class LocalizationString extends Translations {

  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      'title': 'LandSlide Report',
      'tool': 'tool',
      'settings': 'Settings',
      'dashboard': 'Dashboard',
      'change_password': 'Change Mobile No',
      'help_center': 'Help Center',
      'faq': 'FAQ',
      'profile_title': 'Profile',
      'profile_info': 'Profile Info',
      'profile_info_name': 'Full Name',
      'profile_info_email': 'Email Address',
      'profile_info_address': 'Address',
      'profile_info_update_button': 'Update Profile Info',
      'profile_language_select': 'Select Language',
      'profile_logout': 'Logout',
      'profile_logout_text': 'Logging out? We will be here when you are back!',
      'dashboard_sidebar_important_video': 'App Manual',
      'dashboard_sidebar_about_us': 'About Us',
      'dashboard_sidebar_privacy_policy': 'Privacy Policy',
      'dashboard_rainfall': 'Rainfall',
      'dashboard_humidity': 'Humidity',
      'dashboard_wind': 'Wind Speed',
      'dashboard_time_good_morning': "Good Morning",
      'dashboard_time_good_noon': "Good Noon",
      'dashboard_time_good_afternoon': "Good Afternoon",
      'dashboard_time_good_evening': "Good Evening",
      'dashboard_time_good_night': "Good Night",
      'dashboard_weather_forecast': 'Weather\nForecast',
      'dashboard_weather_alert': 'Weather\nAlert',
      'dashboard_flood_forecast': 'Flood\nForecast',
      'dashboard_crop_advisory': 'Crop\nAdvisory',
      'dashboard_pest_disease': 'Disease\nAlert',
      'dashboard_pest_disease_information': 'Disease\nInformation',
      'dashboard_task_reminder': 'Task\nReminder',
      'dashboard_advisory_bulletin': 'Advisory\nBulletin',
      'community_connection': 'Community\nConnection',
      'weather_forecast': 'Weather Forecast',
      'wf_title': 'Weather Forecast',
      'wf_subtitle': 'Weather forecast for next 10 days',
      'wf_temp': 'Temparature',
      'wf_rf': 'Rainfall',
      'wf_rh': 'Humidity',
      'wf_wind': 'Wind Speed',
      'survey_data': 'Survey Data',
      'today_weather': 'Today\'s Weather',
      'landslide_frequency': 'Landslide Frequency',
      'landslide_frequency_overtime': 'Frequency Over Time',
      'my_survey': 'My Surveys',
      'survey_question': 'Survey Question',
      'survey_success': 'Survey submitted successfully',
      'survey_status': 'Survey Status',
      'survey_status_msg': 'This survey is already completed',
      'no_surveys': 'No surveys found',
      'create_survey': 'Create Survey',
      'survey_title': 'Survey Title',
      'enter_title': 'Enter title',
      'validation': 'Validation',
      'title_required': 'Title is required',
      'create_btn': 'Create',
      'instructions': 'Instructions',
      'survey_instructions': 'Select a place where the event happened.\n\nYou can tap on the map to select the location.\nYou can also drag the marker to fine-tune it.',
      'ok': 'OK',
      'no_questions': 'No questions found',
      'select_location': 'Select Location',
      'location_selected': 'Event Location',
      'latitude': 'Latitude: ',
      'longitude': 'Longitude: ',
      'distance_location': 'Distance from your location:',
      'again_btn': 'Again',
      'confirm_btn': 'Confirm',
      'distance_snackbar': 'Distance from your location being copied: ',
      'delete_survey': 'Delete Survey !',
      'delete_survey_msg': 'Are you sure you want to delete this survey?',
      'yes': 'YES',
      'no': 'NO',
      'upload_failed': 'Upload failed',
      'upload_failed_msg': 'Image could\'nt upload. Image size more then 2 MB',
      'notification': 'Notification',
      'alert': 'Alert',
      'normal': 'Normal',
      'time': 'Time',
      'measurement': 'Measurement',
      'station': 'Station',
      'status': 'Status',
    },
    'bn_BD': {
      'title': 'LandSlide Report',
      'tool': 'tool',
      'settings': 'সেটিংস',
      'dashboard': 'ড্যাশবোর্ড',
      'change_password': 'মোবাইল নম্বর পরিবর্তন',
      'help_center': 'সাহায্য কেন্দ্র',
      'faq': 'জিজ্ঞাসিত প্রশ্নাবলী',
      'profile_title': 'প্রোফাইল',
      'profile_info': 'প্রোফাইল বিত্রান্ত',
      'profile_info_name': 'পুরো নাম',
      'profile_info_email': 'ইমেল এড্রেস',
      'profile_info_address': 'ঠিকানা',
      'profile_info_update_button': 'প্রোফাইল ইনফো হালনাগাদ করুণ',
      'profile_language_select': 'ভাষা পরিবর্তন',
      'profile_logout': 'লগ আউট',
      'profile_logout_text': 'তুমি কী প্রস্থান করতে চাও? আমাদের আবার দেখা হবে তুমি যখন ফিরে আসবে।',
      'dashboard_sidebar_important_video': 'অ্যাপ ম্যানুয়াল',
      'dashboard_sidebar_about_us': 'আমাদের সম্পর্কে',
      'dashboard_sidebar_privacy_policy': 'গোপনীয়তা নীতি',
      'dashboard_rainfall': 'বৃষ্টিপাত',
      'dashboard_humidity': 'আর্দ্রতা',
      'dashboard_wind': 'বাতাসের গতি',
      'dashboard_time_good_morning': "শুভ সকাল",
      'dashboard_time_good_noon': "শুভ দুপুর",
      'dashboard_time_good_afternoon': "শুভ বিকাল",
      'dashboard_time_good_evening': "শুভ সন্ধা",
      'dashboard_time_good_night': "শুভ রাত্রি",
      'dashboard_weather_forecast': 'আবহাওয়া\nপূর্বাভাস',
      'dashboard_weather_alert': 'আবহাওয়া\nসতর্কবার্তা',
      'dashboard_flood_forecast': 'বন্যা\nপূর্বাভাস',
      'dashboard_crop_advisory': 'ফসল\nপরামর্শ',
      'dashboard_pest_disease': 'রোগের\nসতর্কতা',
      'dashboard_pest_disease_information': 'রোগের\nতথ্য',
      'dashboard_task_reminder': 'টাস্ক\nরিমাইন্ডার',
      'dashboard_advisory_bulletin': 'এডভাইজারি\nবুলেটিন',
      'community_connection': 'জনসাধারণ\nসংযোগ',
      'weather_forecast': 'আবহাওয়া পূর্বাভাস',
      'wf_title': 'আবহাওয়া পূর্বাভাস',
      'wf_subtitle': 'পরবর্তী ১০ দিনের আবহাওয়া পূর্বাভাস',
      'wf_temp': 'তাপমাত্রা',
      'wf_rf': 'বৃষ্টিপাত',
      'wf_rh': 'আপেক্ষিক আর্দ্রতা',
      'wf_wind': 'বাতাসের গতি',
      'survey_data': 'জরিপ তথ্য',
      'today_weather': 'আজকের আবহাওয়া',
      'landslide_frequency': 'ভূমিধসের পুনরাবৃত্তির হার',
      'landslide_frequency_overtime': 'সময়ের সাথে পুনরাবৃত্তির হার',
      'my_survey': 'আমার জরিপ সমূহ',
      'survey_question': 'জরিপের প্রশ্ন',
      'survey_success': 'জরিপ সফলভাবে জমা হয়েছে',
      'survey_status': 'জরিপের অবস্থা',
      'no_surveys': 'কোন জরিপ পাওয়া যায়নি',
      'survey_status_msg': 'এই জরিপটি ইতিমধ্যে সম্পন্ন হয়েছে',
      'create_survey': 'জরিপ তৈরি করুন',
      'survey_title': 'জরিপের শিরোনাম',
      'enter_title': 'শিরোনাম লিখুন',
      'validation': 'ভ্যালিডেশন',
      'title_required': 'শিরোনাম আবশ্যক',
      'create_btn': 'তৈরি করুন',
      'select_location': 'অবস্থান নির্বাচন করুন',
      'instructions': 'নির্দেশাবলী',
      'survey_instructions': 'একটি স্থান নির্বাচন করুন যেখানে ঘটনাটি ঘটেছে।\n\nআপনি মানচিত্রে ট্যাপ করে অবস্থান নির্বাচন করতে পারেন।\nআপনি ট্যাপ করার পর এটি আরও সঠিকভাবে সেট করার জন্য পিন মার্কারটিকে সরা নড়া করতে পারেন।',
      'ok': 'ওকে',
      'no_questions': 'কোন প্রশ্ন পাওয়া যায়নি',
      'location_selected': 'আপনার ঘটনাস্থল',
      'latitude': 'অক্ষাংশ: ',
      'longitude': 'দ্রাঘিমাংশ: ',
      'distance_location': 'আপনার অবস্থান থেকে দূরত্ব:',
      'again_btn': 'আবার',
      'confirm_btn': 'নিশ্চিত করুন',
      'distance_snackbar': 'আপনার অবস্থান থেকে দূরত্ব কপি করা হয়েছে: ',
      'delete_survey': 'জরিপ মুছুন !',
      'delete_survey_msg': 'আপনি কি নিশ্চিত যে আপনি এই জরিপটি মুছতে চান?',
      'yes': 'হ্যাঁ',
      'no': 'না',
      'upload_failed': 'আপলোড ব্যর্থ',
      'upload_failed_msg': 'ছবি আপলোড করতে ব্যর্থ। ছবি সাইজ ২ এমবির বেশি',
      'notification': 'নোটিফিকেশন',
      'alert': 'সতর্কতা',
      'normal': 'সাধারণ',
      'time': 'সময়',
      'measurement': 'পরিমাপ',
      'station': 'স্টেশন',
      'status': 'অবস্থা',
    }
  };
}
